name: Release to GitHub
on: 
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        id: semantic
        with:
          branches: |
            [
              'main'
            ]
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Output new release version
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
